Parameters:
  FunctionCodeSha:
    Type: String

  LaCrosseDeviceId:
    Type: String

  WundergroundId:
    Type: String

  WundergroundPassword:
    Type: String

  AlarmEmail:
    Type: String

Resources:
  Reader:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://mark-wainwright-shared-cfn-assets-us-east-1.s3.amazonaws.com/templates/scheduled-function.yml
      Parameters:
        ServiceName: !Ref AWS::StackName
        ComponentName: reader

        FunctionCodeSha: !Ref FunctionCodeSha
        FunctionEnvironmentVariablesJson: !Sub |
          {
            "LA_CROSSE_DEVICE_ID": "${LaCrosseDeviceId}",
            "S3_BUCKET_NAME": "${ObservationsBucket}",
            "THERMO_HYGRO_ENABLED": true,
            "PRESSURE_ENABLED": true,
            "RAIN_ENABLED": false,
            "WIND_ENABLED": true,
            "INDOOR_THERMO_HYGRO_ENABLED": true
          }
        FunctionHandler: reader.handler
        FunctionMemorySize: 1024
        FunctionTimeoutSecs: 20
        FunctionPayload: '{"count": 3}'

        ScheduleExpression: rate(15 minutes) # La Crosse usually publishes a new observation every 7-17 mins

  Writer:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://mark-wainwright-shared-cfn-assets-us-east-1.s3.amazonaws.com/templates/queue-function.yml
      Parameters:
        ServiceName: !Ref AWS::StackName
        ComponentName: writer

        FunctionCodeSha: !Ref FunctionCodeSha
        FunctionEnvironmentVariablesJson: !Sub |
          {
            "WUNDERGROUND_ID": "${WundergroundId}",
            "WUNDERGROUND_PWD": "${WundergroundPassword}"
          }
        FunctionHandler: writer.handler
        FunctionMemorySize: 1024
        FunctionTimeoutSecs: 20

        MessageSourceArn: !Sub arn:aws:s3:*:*:${AWS::StackName}-observations

  ObservationsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-observations
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      NotificationConfiguration:
        QueueConfigurations:
          - Event: s3:ObjectCreated:Put
            Queue: !GetAtt Writer.Outputs.QueueArn

  ObservationsBucketReadPolicy:
    Type: AWS::IAM::Policy
    Properties:
      Roles:
        - !GetAtt Reader.Outputs.FunctionRoleName
        - !GetAtt Writer.Outputs.FunctionRoleName
      PolicyName: observations-bucket-read
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action: s3:ListBucket
            Resource: !GetAtt ObservationsBucket.Arn
          - Effect: Allow
            Action: s3:GetObject
            Resource: !Sub '${ObservationsBucket.Arn}/*'

  ObservationsBucketWritePolicy:
    Type: AWS::IAM::Policy
    Properties:
      Roles:
        - !GetAtt Reader.Outputs.FunctionRoleName
      PolicyName: observations-bucket-write
      PolicyDocument:
        Statement:
          - Effect: Allow
            Action: s3:PutObject
            Resource: !Sub '${ObservationsBucket.Arn}/*'
