$imports:
  package: '../package.json'
  alarmEmail: env:ALARM_EMAIL
  functionCodeSha: env:FUNCTION_CODE_SHA
  laCrosseDeviceId: env:LA_CROSSE_DEVICE_ID
  wundergroundId: env:WUNDERGROUND_ID
  wundergroundPassword: env:WUNDERGROUND_PWD

StackName: !$ package.name
Template: ./cfn-template.yml

OnFailure: DELETE
Capabilities:
  - CAPABILITY_NAMED_IAM

Parameters:
  AlarmEmail: !$ alarmEmail
  FunctionCodeSha: !$ functionCodeSha
  LaCrosseDeviceId: !$ laCrosseDeviceId
  WundergroundId: !$ wundergroundId
  WundergroundPassword: !$ wundergroundPassword
