name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Deploy
        run: npm run deploy -- --verbose
        env:
          ALARM_EMAIL: ${{ secrets.ALARM_EMAIL }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          LA_CROSSE_DEVICE_ID: ${{ secrets.LA_CROSSE_DEVICE_ID }}
          WUNDERGROUND_ID: ${{ secrets.WUNDERGROUND_ID }}
          WUNDERGROUND_PWD: ${{ secrets.WUNDERGROUND_PWD }}
